export const API_URL = {
  // BASEURL: "http://localhost:8001/",
  BASEURL: "https://instachat-server-33lx.onrender.com/",
  SIGNUP: "signup",
  SIGNIN: "signin",
  VERIFYEMAIL: "verifyemail",
  FORGOTPASSWORD: "forgotpassword",
  NEWSFEED: "newsfeed",
  POSTLIKE: "posts/like",
  POSTLIKELIST: "posts/likelist",
  POSTDELETE: "posts/delete",
  POSTCOMMENT: "posts/comment",
  POSTCOMMENTDELETE: "posts/comment/delete",
  MYFRIENDS: "myFriends",
  FRIENDREQUESTS: "friendRequests",
  FRIENDSUGGESTIONS: "friends/suggestions",
  FRIENDREQUESTACCEPT: "friend-request/accept",
  FRIENDREQUESTDELETE: "friend-request/delete",
  DELETEFRIEND: "deletefriend",
  FRIENDREQUESTSEND: "friend-request/send",
  FRIENDREQUESTCANCEL: "friend-request/cancel",
  ALLUSER: "allUsersExceptMeAndMyFriends",
  UPDATEPROFILE: "update-profile",
  CREATEPOSTS: "posts",
  GETNOTIFICATIONS: "notifications",  
  MESSAGESEND: "message/send",  
  MESSAGEHISTORY: "message/history/",  
  GETPROFILE: "getprofile",  
  GROUPCREATE: "group/create",  
  GROUPDELETE: "group/delete",  
  GROUPEDIT: "group/edit",  
  GROUP: "group",  
};
